spring:
  application:
    name: school-service
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: dodo
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: jdbc:postgresql://localhost:5432/school
    user: dodo
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/school
    username: dodo
  cache:
    type: redis
    redis:
      enable-statistics: off
  security:
    user:
      name: dodo
      password: dodo
      roles:
        - manager
        - dev
        - customer
  devtools:
    add-properties: true

server:
  port: 8080
logging:
  level:
    root: info


